todo_manager/config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    get 'filter', on: :collection
    get 'pending', on: :collection
    patch 'mark'
  end
  
  resources :tags
  

  root 'welcome#index'

end

todo_manager/app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, format: { with: /\A[a-zA-Z0-9_ -]+\z/,
  message: "only allows numbers and letters" }

  has_many :taggings
  has_many :tasks, through: :taggings

  def self.delete_empty_tags
  	Tag.all.each do |tag|
  		if (tag.tasks.count == 0)
  			tag.destroy
  		end
  	end
  end

end

todo_manager/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :task
end

todo_manager/app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 2 }
  has_many :taggings
  has_many :tags, through: :taggings

  validate do |task|
    task.tags.each do |tag|
      next if tag.valid?
      tag.errors.full_messages.each do |msg|
        # you can customize the error message here:
        task.errors[:base] << "Tag Error: #{msg}"
      end
    end
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).tasks
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end
  
  def tag_array
    tags.map(&:name)
  end
  
  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.find_or_create_by(name: n.strip)
    end
  end

end

todo_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo_manager/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :all_tags, only: [:index, :create, :update, :destroy]
	respond_to :html, :js

	def new
		@tag = Tag.new
	end

	def create
		flash[:notice] = "New tag successfully created!"
	  @tag = Tag.new(tag_params)
	 
	  if @tag.save
	    redirect_to tags_path
	  else
	    render 'new'
	   end
	end

	def edit
	  @tag = Tag.find(params[:id])
	end

	def update
	  @tag = Tag.find(params[:id])
	 
	  if @tag.update(tag_params)
	    redirect_to tags_path
	  else
	    render 'edit'
	  end
	end


	def destroy
	  @tag = Tag.find(params[:id])
	  @tag.destroy
	 
	  redirect_to tags_path
	end

	private
		def all_tags
      @tags = Tag.all
  	end

	  def tag_params
	    params.require(:tag).permit(:name, :color)
	  end
end

todo_manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :all_tasks, only: [:index, :create, :update, :mark, :destroy]
  respond_to :html, :js

	def pending
		@tasks = []
		Task.order(:due_date).each do |t|
			if t.due_date >= Time.now.to_datetime && (!(t.is_complete))
				@tasks.push(t)
			end
		end
	end

  def new
  	@task = Task.new
  end

	def edit
	  @task = Task.find(params[:id])
	end

	def create
		flash[:notice] = "New Task successfully created!"
	  @task = Task.new(task_params)
	  if (!@task.save)
	    render 'new'
	  end
	end

	def update
	  @task = Task.find(params[:id])
	 
	  if @task.update(task_params)
	    # redirect_to @task
	  else
	    render 'edit'
	  end
	rescue
		@task.errors[:base] << "Error in tags name. Only allow alphanumeric characters, white space and underscore"
		render 'edit'
	end

	def destroy
	  @task = Task.find(params[:id])
	  @task.destroy
	  Tag.delete_empty_tags
	  redirect_to tasks_path
	end

	def filter
		@tasks  = Task.tagged_with(params[:format])
	end

	def mark
		@task = Task.find(params[:task_id])
		if (@task.is_complete)
			@task.update_attribute(:is_complete, false)
		else
			@task.update_attribute(:is_complete, true)
		end
		# redirect_to tasks_path
	end

	private

	  def all_tasks
      @tasks = Task.all
  	end

	  def task_params
	    params.require(:task).permit(:title, :text, :due_date, :tag_list)
	  end

end

todo_manager/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

todo_manager/app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

todo_manager/app/helpers/tags_helper.rb
module TagsHelper
end

todo_manager/app/helpers/tasks_helper.rb
module TasksHelper
end

todo_manager/app/helpers/welcome_helper.rb
module WelcomeHelper
end

todo_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoManager</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="panel panel-default tasks-container">
      <div class="panel-heading">
        <h2 class="app-title">HL Todo Manager</h2>
      </div>
      <div class="panel-body">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

todo_manager/app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>

  <% if @tag.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h4>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
  </div>
  <div class="form-group">
    <%= f.label :color, "Tags (separated by commas)" %><br />
    <%= f.color_field :color, class: 'form-control' %>
  </div>
  <br>
  <p>
    <%= f.submit nil, class: 'btn btn-success'%>
    <a class="btn btn-danger js-close">Cancel</a>
  </p>
</form>
<% end %>

todo_manager/app/views/tags/_table.html.erb
<table class="table table-striped tags-table">
  <thead>
  <tr>
    <th>Tag Name</th>
    <th colspan="2">Tasks</th>
  </tr>
  </thead>
  <tbody remote: true>
  <% @tags.each do |tag| %>
    <tr id="<%= tag.id %>">
      <td >
        <%= link_to tag.name, filter_tasks_path(tag.name), class: 'tasks-tag label label-default', style: "background-color: " + tag.color %>
      </td>
      <td>
        <% tag.tasks.each do |task| %>
        <%= link_to task.title+';', task_path(task)%>
        <% end %>
      </td>
      <td class="tasks-action-column">
        <%= link_to raw('<i class="fa fa-pencil"></i>'), 
          edit_tag_path(tag), 
          class: 'btn btn-default btn-xs' %>
        <%= link_to raw('<i class="fa fa-trash"></i>'), 
          tag_path(tag),
          method: :delete, remote: true,
          data: { confirm: 'Are you sure?' },
          class: 'btn btn-default btn-xs' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

todo_manager/app/views/tags/edit.html.erb
<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tags_path, 
      class: 'btn btn-default btn-sm main-action-button' %>

<h1>Edit Tag</h1>
<hr>
 
<%= form_for @tag do |f| %>

  <% if @tag.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h4>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
  </div>
  <div class="form-group">
    <%= f.label :color, "Tags (separated by commas)" %><br />
    <%= f.color_field :color, class: 'form-control' %>
  </div>
  <br>
  <p>
    <%= f.submit nil, class: 'btn btn-success'%>
  </p>
</form>
<% end %>

todo_manager/app/views/tags/edit.js.erb
$('#tag-form').html("<%= escape_javascript (render 'form') %>");
$('#tag-form').slideDown(300);

todo_manager/app/views/tags/index.html.erb
<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tasks_path, 
      class: 'btn btn-default btn-sm main-action-button' %>
<%= link_to raw('<i class="fa fa-plus"></i> New Tag'), 
    new_tag_path, 
    class: 'btn btn-sm btn-success main-action-button' %>

<h1>Manage Tags</h1>
<hr>
<table class="table table-striped tasks-table">
  <tr>
    <th>Tag Name</th>
    <th colspan="2">Tasks</th>
  </tr>
  <% @tags.each do |tag| %>
    <tr>
      <td>
        <%= link_to tag.name, filter_tasks_path(tag.name), class: 'tasks-tag label label-default', style: "background-color: " + tag.color %>
        <br>
        <div class="task-form" id="tag-form"></div>
      </td>
      <td>
        <% tag.tasks.each do |task| %>
        <%= link_to task.title+';', task_path(task)%>
        <% end %>
      </td>
      <td class="tasks-action-column">
        <%= link_to raw('<i class="fa fa-pencil"></i>'), 
          edit_tag_path(tag), remote: true,
          class: 'btn btn-default btn-xs' %>
        <%= link_to raw('<i class="fa fa-trash"></i>'), 
          tag_path(tag),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'btn btn-default btn-xs' %>
      </td>
    </tr>
  <% end %>
</table>

todo_manager/app/views/tags/new.html.erb
<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tasks_path, 
      class: 'btn btn-default btn-sm main-action-button' %>

<h1>New Tag</h1>
<hr>

<%= render 'form' %>

todo_manager/app/views/tags/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tags_path, 
      class: 'btn btn-default btn-sm main-action-button' %>

<h1>All Tasks
<% if @tag_name %>
with Tag
<%= @tag_name %>
<% end %>
</h1>
<div class="row">
  <div class="col-md-9">  
    <table class="table table-striped tasks-table">
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Due</th>
        <th colspan="2">Tags</th>
      </tr>
     
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.text %></td>
          <td><%= task.due_date %></td>
          <td>
            <% task.tag_array.each do |tag| %>
              <%= link_to tag, tag_path(tag), class: 'tasks-tag label label-default'%>
            <% end %>
          </td>
          <td class="tasks-action-column">
            <%= link_to raw('<i class="fa fa-search"></i>'),
              task_path(task), 
              class: 'btn btn-default btn-xs' %>
            <%= link_to raw('<i class="fa fa-pencil"></i>'), 
              edit_task_path(task), 
              class: 'btn btn-default btn-xs' %>
            <%= link_to raw('<i class="fa fa-trash"></i>'), 
              task_path(task),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-3 tags-container">
    <div class="panel panel-default">
      <div class="panel-heading">Tags <%= link_to raw('<i class="fa fa-pencil"></i>'), tags_path, class: 'tags-edit' %></div>
      <div class="panel-body">
        <% Tag.all.each do |tag| %>
          <%= link_to tag.name, tag_path(tag.name), class: 'tasks-tag label label-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

todo_manager/app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h4>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title' %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: 'form-control', placeholder: 'Enter text' %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %>
    <%= f.datetime_local_field :due_date, class: 'form-control datepicker' %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_area :tag_list, class: 'form-control', placeholder: 'Enter your tags, e.g: Health, Sport...'%>
  </div>
  <br>
  <p>
    <%= f.submit nil, class: 'btn btn-success'%>
    <a class="btn btn-danger js-close">Cancel</a>
  </p>
<% end %>

todo_manager/app/views/tasks/_table.html.erb
<table class="table table-striped tasks-table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Due</th>
    <th colspan="2">Tags</th>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.text %></td>
      <td><%= task.due_date %></td>
      <td>
        <% task.tags.each do |tag| %>
          <%= link_to tag.name, filter_tasks_path(tag.name), class: 'tasks-tag label label-default', style: "background-color: " + tag.color %>
        <% end %>
      </td>
      <td class="tasks-action-column">
        <%= link_to raw('<i class="fa fa-pencil"></i>'), 
          edit_task_path(task), remote: true,
          class: 'btn btn-default btn-xs' %>
        <%= link_to raw('<i class="fa fa-trash"></i>'), 
          task_path(task),
          method: :delete, 
          data: { confirm: 'Are you sure to delete?' },
          class: 'btn btn-default btn-xs' %>
        <% if (task.is_complete) %>
        <%= link_to raw('<i class="fa fa-undo"></i>'), 
          task_mark_path(task), remote: true,
          method: :PATCH,
          data: { confirm: 'Are you sure that you want to add this to pending tasks?' },
          class: 'btn btn-default btn-xs' %>
        <% else %> 
        <%= link_to raw('<i class="fa fa-check"></i>'), 
          task_mark_path(task),
          method: :PATCH, remote: true,
          data: { confirm: 'Are you sure that you have completed this task?' },
          class: 'btn btn-default btn-xs' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

todo_manager/app/views/tasks/_tagCloud.html.erb
<div class="col-md-3 tags-container">
  <div class="panel panel-default">
    <div class="panel-heading">Tags <%= link_to raw('<i class="fa fa-pencil"></i>'), tags_path, class: 'tags-edit' %></div>
    <div class="panel-body">
      <% Tag.all.each do |tag| %>
        <%= link_to tag.name, filter_tasks_path(tag.name), class: 'tasks-tag label label-default', style: "background-color: " + tag.color %>
      <% end %>
    </div>
  </div>
</div>

todo_manager/app/views/tasks/create.js.erb
$('#tasks-table').html("<%= j (render 'table') %>");
$('#tag-cloud').html("<%= j (render 'tagCloud') %>");
$('#task-form').slideUp(300);

todo_manager/app/views/tasks/edit.js.erb
$('#task-form').html("<%= escape_javascript (render 'form') %>");
$('#task-form').slideDown(300);

todo_manager/app/views/tasks/filter.html.erb
<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tasks_path, 
      class: 'btn btn-default btn-sm main-action-button' %>
<%= link_to raw('<i class="fa fa-plus"></i> New Task'), 
    new_task_path, remote: true,
    class: 'btn btn-sm btn-success main-action-button' %>
<% if (@tasks != []) %>
<h1>All Tasks with Tag " <%= params[:format] %> " </h1>
<div class="row">
  <div class="col-md-9">  
    <div id='tasks-table'><%= render 'table' %></div>
    <div class="task-form" id="task-form"></div>
  </div>
  <div id='tag-cloud'>  
    <%= render 'tagCloud' %>
  </div>
</div>
<% else %>
<br><br>
<div class="alert alert-warning"><h1> No task has tag " <%= params[:format] %> " </h1></div>
<% end %>

todo_manager/app/views/tasks/index.html.erb
<%= link_to raw('<i class="fa fa-plus"></i> New Task'), 
    new_task_path, remote: true,
    class: 'btn btn-sm btn-success main-action-button' %>
<div id="pending-btn" >
<%= link_to raw('View Pending Tasks'), 
    pending_tasks_path, remote: true,
    class: 'btn btn-sm btn-primary main-action-button' %>
</div>
<div id="back-btn" style="display:none">
<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'),
      tasks_path,
      class: 'btn btn-default btn-sm main-action-button' %>
</div>
<h1 id="title">All Tasks </h1>
<div class="row">
  <div class="col-md-9">  
    <div id='tasks-table'><%= render 'table' %></div>
    <div class="task-form" id="task-form"></div>
  </div>
  <div id='tag-cloud'>  
    <%= render 'tagCloud' %>
  </div>
</div>

todo_manager/app/views/tasks/mark.js.erb
$('#tasks-table').html("<%= j (render 'table') %>");

todo_manager/app/views/tasks/new.js.erb
$('#task-form').html("<%= escape_javascript (render 'form') %>");
$('#task-form').slideDown(300);

todo_manager/app/views/tasks/pending.js.erb
$('#tasks-table').html("<%= j (render 'table') %>");
$('#back-btn').show();
$('#pending-btn').hide();

todo_manager/app/views/tasks/update.js.erb
$('#tasks-table').html("<%= j (render 'table') %>");
$('#tag-cloud').html("<%= j (render 'tagCloud') %>");
$('#task-form').slideUp(300);

todo_manager/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Todos List', controller: 'tasks' %>